export const ADD_COMMENT = "ADD_COMMENT";
export const GAMES_LOADING = "GAMES_LOADING";
export const GAMES_FAILED = "GAMES_FAILED";
export const ADD_GAMES = "ADD_GAMES";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const PROMOS_LOADING = "PROMOS_LOADING";
export const ADD_PROMOS = "ADD_PROMOS";
export const PROMOS_FAILED = "PROMOS_FAILED";
export const LEADERS_LOADING = "LEADERS_LOADING";
export const LEADERS_FAILED = "LEADERS_FAILED";
export const ADD_LEADERS = "ADD_LEADERS";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const EVENTS_LOADING = "EVENTS_LOADING";
export const EVENTS_FAILED = "EVENTS_FAILED";
export const ADD_EVENTS = "ADD_EVENTS";
export const ADD_EVENT = "ADD_EVENT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
